"""Add billing_notifications table

Revision ID: 4326f3baaf18
Revises: 4afc7c6a1fe1
Create Date: 2025-12-30 21:20:57.574715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4326f3baaf18'
down_revision: Union[str, Sequence[str], None] = '4afc7c6a1fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_request_id', sa.Integer(), nullable=False),
    sa.Column('billing_user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_request_id'], ['payment_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_notifications_billing_user_id'), 'billing_notifications', ['billing_user_id'], unique=False)
    op.create_index(op.f('ix_billing_notifications_payment_request_id'), 'billing_notifications', ['payment_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_notifications_payment_request_id'), table_name='billing_notifications')
    op.drop_index(op.f('ix_billing_notifications_billing_user_id'), table_name='billing_notifications')
    op.drop_table('billing_notifications')
    # ### end Alembic commands ###
