"""make_tracker_login_optional

Revision ID: 4afc7c6a1fe1
Revises: 92f0ae364202
Create Date: 2025-12-30 06:18:20.986759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afc7c6a1fe1'
down_revision: Union[str, Sequence[str], None] = '92f0ae364202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tracker_login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tracker_login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
