"""add_is_active_to_users

Revision ID: d29d49e2fc70
Revises: 4326f3baaf18
Create Date: 2026-01-09 16:45:14.436330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29d49e2fc70'
down_revision: Union[str, Sequence[str], None] = '4326f3baaf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавляем колонку как nullable
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Устанавливаем значение True для всех существующих записей
    op.execute("UPDATE users SET is_active = true")
    # Делаем колонку NOT NULL
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
